### ISSUE TITLE
OOM error [fatal error: runtime: out of memory], 96 active channels, 1GB

### ISSUE THREAD

**Issue by AbelLykens** [lightninglabs/faraday#69]
I did:
```
go get -d github.com/lightninglabs/faraday
cd $GOPATH/src/github.com/lightninglabs/faraday
git clone
make && make install
```
Set up Faraday to connect to bitcoind backend. Seems to work.

I run faraday. Then in terminal2 I do `frcli insights`. Memory + Swap fills up and faraday crashes. Frcli command tells me then `[frcli] rpc error: code = Unavailable desc = transport is closing`.

I have 96 active channels. Server specs:
```
# free -m
              total        used        free      shared  buff/cache   available
Mem:           1919         522        1135           1         261        1294
Swap:          1639         511        1128
```

@guggero suggested to open an issue ;)

**Comment by AbelLykens** [comment]
```# ./faraday
2020-08-28 07:21:57.681 [INF] FRPC: Starting gRPC listener
2020-08-28 07:21:57.681 [INF] FRPC: gRPC server listening on 127.0.0.1:8465
2020-08-28 07:21:57.681 [INF] FRPC: REST proxy disabled
fatal error: runtime: out of memory

runtime stack:
runtime.throw(0xef7a24, 0x16)
        /usr/local/go/src/runtime/panic.go:774 +0x72
runtime.sysMap(0xc0a0000000, 0x2c000000, 0x181ad98)
        /usr/local/go/src/runtime/mem_linux.go:169 +0xc5
runtime.(*mheap).sysAlloc(0x1802200, 0x2bc60000, 0x0, 0x0)
        /usr/local/go/src/runtime/malloc.go:701 +0x1cd
runtime.(*mheap).grow(0x1802200, 0x15e30, 0xffffffff)
        /usr/local/go/src/runtime/mheap.go:1252 +0x42
runtime.(*mheap).allocSpanLocked(0x1802200, 0x15e30, 0x181ada8, 0x9e)
        /usr/local/go/src/runtime/mheap.go:1163 +0x291
runtime.(*mheap).alloc_m(0x1802200, 0x15e30, 0x7f8bb80a0100, 0x7ffde6a25e98)
        /usr/local/go/src/runtime/mheap.go:1015 +0xc2
runtime.(*mheap).alloc.func1()
        /usr/local/go/src/runtime/mheap.go:1086 +0x4c
runtime.(*mheap).alloc(0x1802200, 0x15e30, 0x7ffde6010100, 0x7f8bb80a61d8)
        /usr/local/go/src/runtime/mheap.go:1085 +0x8a
runtime.largeAlloc(0x2bc60000, 0x7f8bf24f0001, 0x7f8bb80a61d8)
        /usr/local/go/src/runtime/malloc.go:1138 +0x97
runtime.mallocgc.func1()
        /usr/local/go/src/runtime/malloc.go:1033 +0x46
runtime.systemstack(0x45a734)
        /usr/local/go/src/runtime/asm_amd64.s:370 +0x66
runtime.mstart()
        /usr/local/go/src/runtime/proc.go:1146

goroutine 51 [running]:
runtime.systemstack_switch()
        /usr/local/go/src/runtime/asm_amd64.s:330 fp=0xc000145248 sp=0xc000145240 pc=0x45a830
runtime.mallocgc(0x2bc60000, 0xe30a40, 0xc000145301, 0x40f7db)
        /usr/local/go/src/runtime/malloc.go:1032 +0x895 fp=0xc0001452e8 sp=0xc000145248 pc=0x40e005
runtime.growslice(0xe30a40, 0xc06be1c000, 0xbac400, 0xbac400, 0xbac401, 0xc06be1c000, 0x956955, 0xbac400)
        /usr/local/go/src/runtime/slice.go:181 +0x1e2 fp=0xc000145350 sp=0xc0001452e8 pc=0x445472
github.com/lightninglabs/faraday/revenue.getEvents.func1(0x0, 0x1f4, 0x0, 0x1f4, 0x0, 0x0)
        /root/go/src/github.com/lightninglabs/faraday/revenue/revenue.go:123 +0x3c1 fp=0xc0001454f0 sp=0xc000145350 pc=0xc2b7e1
github.com/lightninglabs/faraday/paginater.QueryPaginated(0x116a3c0, 0xc0000be040, 0xc000145588, 0x0, 0x1f4, 0x1da0044e902715d3, 0x29)
        /root/go/src/github.com/lightninglabs/faraday/paginater/paginater.go:20 +0x45 fp=0xc000145538 sp=0xc0001454f0 pc=0x7bc365
github.com/lightninglabs/faraday/revenue.getEvents(0xc000145648, 0xc0002f8780, 0xc000145614, 0xc0004ed298, 0x0, 0x203000, 0x2)
        /root/go/src/github.com/lightninglabs/faraday/revenue/revenue.go:136 +0xa5 fp=0xc0001455b8 sp=0xc000145538 pc=0xc2ad75
github.com/lightninglabs/faraday/revenue.GetRevenueReport(0xc00000f220, 0xc0003047e0, 0xc0002da300, 0x0)
        /root/go/src/github.com/lightninglabs/faraday/revenue/revenue.go:59 +0x370 fp=0xc000145928 sp=0xc0001455b8 pc=0xc2abc0
github.com/lightninglabs/faraday/frdrpc.channelInsights(0x116a440, 0xc0003047e0, 0xc0002da300, 0x0, 0x0, 0x0, 0xc000310100, 0x1172520)
        /root/go/src/github.com/lightninglabs/faraday/frdrpc/channel_insights.go:22 +0xb9 fp=0xc0001459d0 sp=0xc000145928 pc=0xc4b4b9
github.com/lightninglabs/faraday/frdrpc.(*RPCServer).ChannelInsights(0xc0002f84b0, 0x116a440, 0xc0003047e0, 0xc00000f1e0, 0xc0002f84b0, 0xc0003047e0, 0xc00034ca80)
        /root/go/src/github.com/lightninglabs/faraday/frdrpc/rpcserver.go:308 +0x85 fp=0xc000145a20 sp=0xc0001459d0 pc=0xc5b875
github.com/lightninglabs/faraday/frdrpc._FaradayServer_ChannelInsights_Handler(0xe68680, 0xc0002f84b0, 0x116a440, 0xc0003047e0, 0xc0003101e0, 0x0, 0x116a440, 0xc0003047e0, 0x0, 0x0)
        /root/go/src/github.com/lightninglabs/faraday/frdrpc/rpc.pb.go:1908 +0x217 fp=0xc000145a90 sp=0xc000145a20 pc=0xc55fa7
google.golang.org/grpc.(*Server).processUnaryRPC(0xc00008f800, 0x1175940, 0xc000344000, 0xc0002da400, 0xc000304450, 0x17e3c88, 0x0, 0x0, 0x0)
        /root/go/pkg/mod/google.golang.org/grpc@v1.25.1/server.go:1007 +0x460 fp=0xc000145e18 sp=0xc000145a90 pc=0xac0830
google.golang.org/grpc.(*Server).handleStream(0xc00008f800, 0x1175940, 0xc000344000, 0xc0002da400, 0x0)
        /root/go/pkg/mod/google.golang.org/grpc@v1.25.1/server.go:1287 +0xd97 fp=0xc000145f48 sp=0xc000145e18 pc=0xac4757
google.golang.org/grpc.(*Server).serveStreams.func1.1(0xc0000beee0, 0xc00008f800, 0x1175940, 0xc000344000, 0xc0002da400)
        /root/go/pkg/mod/google.golang.org/grpc@v1.25.1/server.go:722 +0xbb fp=0xc000145fb8 sp=0xc000145f48 pc=0xad1a9b
runtime.goexit()
        /usr/local/go/src/runtime/asm_amd64.s:1357 +0x1 fp=0xc000145fc0 sp=0xc000145fb8 pc=0x45c901
created by google.golang.org/grpc.(*Server).serveStreams.func1
        /root/go/pkg/mod/google.golang.org/grpc@v1.25.1/server.go:720 +0xa1

goroutine 1 [chan receive, 1 minutes]:
github.com/lightninglabs/faraday.Main(0x0, 0x0)
        /root/go/src/github.com/lightninglabs/faraday/faraday.go:63 +0x3f3
main.main()
        /root/go/src/github.com/lightninglabs/faraday/cmd/faraday/main.go:12 +0x26

goroutine 8 [syscall, 1 minutes]:
os/signal.signal_recv(0x0)
        /usr/local/go/src/runtime/sigqueue.go:147 +0x9c
os/signal.loop()
        /usr/local/go/src/os/signal/signal_unix.go:23 +0x22
created by os/signal.init.0
        /usr/local/go/src/os/signal/signal_unix.go:29 +0x41

goroutine 9 [select, 1 minutes]:
google.golang.org/grpc.(*ccBalancerWrapper).watcher(0xc00009ad80)
        /root/go/pkg/mod/google.golang.org/grpc@v1.25.1/balancer_conn_wrappers.go:68 +0xc2
created by google.golang.org/grpc.newCCBalancerWrapper
        /root/go/pkg/mod/google.golang.org/grpc@v1.25.1/balancer_conn_wrappers.go:59 +0x16d

goroutine 10 [chan receive, 1 minutes]:
google.golang.org/grpc.(*addrConn).resetTransport(0xc0001c9080)
        /root/go/pkg/mod/google.golang.org/grpc@v1.25.1/clientconn.go:1163 +0x6ac
created by google.golang.org/grpc.(*addrConn).connect
        /root/go/pkg/mod/google.golang.org/grpc@v1.25.1/clientconn.go:800 +0x120

goroutine 26 [IO wait]:
internal/poll.runtime_pollWait(0x7f8bf24f3f88, 0x72, 0xffffffffffffffff)
        /usr/local/go/src/runtime/netpoll.go:184 +0x55
internal/poll.(*pollDesc).wait(0xc00026c098, 0x72, 0x8c00, 0x8cea, 0xffffffffffffffff)
        /usr/local/go/src/internal/poll/fd_poll_runtime.go:87 +0x45
internal/poll.(*pollDesc).waitRead(...)
        /usr/local/go/src/internal/poll/fd_poll_runtime.go:92
internal/poll.(*FD).Read(0xc00026c080, 0xc00035e000, 0x8cea, 0x8cea, 0x0, 0x0, 0x0)
        /usr/local/go/src/internal/poll/fd_unix.go:169 +0x1cf
net.(*netFD).Read(0xc00026c080, 0xc00035e000, 0x8cea, 0x8cea, 0x203010, 0x0, 0x8ce5)
        /usr/local/go/src/net/fd_unix.go:202 +0x4f
net.(*conn).Read(0xc000248028, 0xc00035e000, 0x8cea, 0x8cea, 0x0, 0x0, 0x0)
        /usr/local/go/src/net/net.go:184 +0x68
crypto/tls.(*atLeastReader).Read(0xc04195c2a0, 0xc00035e000, 0x8cea, 0x8cea, 0x27, 0x1151cc0, 0xc0004cf9f0)
        /usr/local/go/src/crypto/tls/conn.go:780 +0x60
bytes.(*Buffer).ReadFrom(0xc0001965d8, 0x1151b80, 0xc04195c2a0, 0x40ba65, 0xd9a060, 0xeb1300)
        /usr/local/go/src/bytes/buffer.go:204 +0xb4
crypto/tls.(*Conn).readFromUntil(0xc000196380, 0x1153020, 0xc000248028, 0x5, 0xc000248028, 0x11)
        /usr/local/go/src/crypto/tls/conn.go:802 +0xec
crypto/tls.(*Conn).readRecordOrCCS(0xc000196380, 0x0, 0x0, 0x0)
        /usr/local/go/src/crypto/tls/conn.go:609 +0x124
crypto/tls.(*Conn).readRecord(...)
        /usr/local/go/src/crypto/tls/conn.go:577
crypto/tls.(*Conn).Read(0xc000196380, 0xc0002a4000, 0x8000, 0x8000, 0x0, 0x0, 0x0)
        /usr/local/go/src/crypto/tls/conn.go:1255 +0x161
bufio.(*Reader).Read(0xc0002a2240, 0xc00028a118, 0x9, 0x9, 0xc000196a80, 0x7f8bf258fd98, 0x0)
        /usr/local/go/src/bufio/bufio.go:226 +0x26a
io.ReadAtLeast(0x11519e0, 0xc0002a2240, 0xc00028a118, 0x9, 0x9, 0x9, 0xa1f375, 0xc04176a28c, 0xc0004cfde8)
        /usr/local/go/src/io/io.go:310 +0x87
io.ReadFull(...)
        /usr/local/go/src/io/io.go:329
golang.org/x/net/http2.readFrameHeader(0xc00028a118, 0x9, 0x9, 0x11519e0, 0xc0002a2240, 0x0, 0xbfca4a1400000000, 0xe13f12e6b, 0x17f8660)
        /root/go/pkg/mod/golang.org/x/net@v0.0.0-20191002035440-2ec189313ef0/http2/frame.go:237 +0x87
golang.org/x/net/http2.(*Framer).ReadFrame(0xc00028a0e0, 0xc04176a280, 0xc04176a280, 0x0, 0x0)
        /root/go/pkg/mod/golang.org/x/net@v0.0.0-20191002035440-2ec189313ef0/http2/frame.go:492 +0xa1
google.golang.org/grpc/internal/transport.(*http2Client).reader(0xc0000b81c0)
        /root/go/pkg/mod/google.golang.org/grpc@v1.25.1/internal/transport/http2_client.go:1250 +0x183
created by google.golang.org/grpc/internal/transport.newHTTP2Client
        /root/go/pkg/mod/google.golang.org/grpc@v1.25.1/internal/transport/http2_client.go:293 +0xd23

goroutine 27 [select]:
google.golang.org/grpc/internal/transport.(*controlBuffer).get(0xc0000c6c30, 0x1, 0x0, 0x0, 0x0, 0x0)
        /root/go/pkg/mod/google.golang.org/grpc@v1.25.1/internal/transport/controlbuf.go:395 +0x122
google.golang.org/grpc/internal/transport.(*loopyWriter).run(0xc0002a2300, 0x0, 0x0)
        /root/go/pkg/mod/google.golang.org/grpc@v1.25.1/internal/transport/controlbuf.go:513 +0x1e3
google.golang.org/grpc/internal/transport.newHTTP2Client.func3(0xc0000b81c0)
        /root/go/pkg/mod/google.golang.org/grpc@v1.25.1/internal/transport/http2_client.go:337 +0x7b
created by google.golang.org/grpc/internal/transport.newHTTP2Client
        /root/go/pkg/mod/google.golang.org/grpc@v1.25.1/internal/transport/http2_client.go:335 +0xec0

goroutine 11 [select, 1 minutes]:
github.com/btcsuite/btcd/rpcclient.(*Client).sendPostHandler(0xc00014e0c0)
        /root/go/pkg/mod/github.com/btcsuite/btcd@v0.20.1-beta.0.20200730232343-1db1b6f8217f/rpcclient/infrastructure.go:768 +0xdc
created by github.com/btcsuite/btcd/rpcclient.(*Client).start
        /root/go/pkg/mod/github.com/btcsuite/btcd@v0.20.1-beta.0.20200730232343-1db1b6f8217f/rpcclient/infrastructure.go:1066 +0x10f

goroutine 13 [select, 1 minutes]:
github.com/lightningnetwork/lnd/signal.mainInterruptHandler()
        /root/go/pkg/mod/github.com/lightningnetwork/lnd@v0.11.0-beta.rc2/signal/signal.go:71 +0x106
created by github.com/lightningnetwork/lnd/signal.Intercept
        /root/go/pkg/mod/github.com/lightningnetwork/lnd@v0.11.0-beta.rc2/signal/signal.go:39 +0xee

goroutine 16 [IO wait, 1 minutes]:
internal/poll.runtime_pollWait(0x7f8bf24f3eb8, 0x72, 0x0)
        /usr/local/go/src/runtime/netpoll.go:184 +0x55
internal/poll.(*pollDesc).wait(0xc0004ac498, 0x72, 0x0, 0x0, 0xee811a)
        /usr/local/go/src/internal/poll/fd_poll_runtime.go:87 +0x45
internal/poll.(*pollDesc).waitRead(...)
        /usr/local/go/src/internal/poll/fd_poll_runtime.go:92
internal/poll.(*FD).Accept(0xc0004ac480, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0)
        /usr/local/go/src/internal/poll/fd_unix.go:384 +0x1f8
net.(*netFD).accept(0xc0004ac480, 0x37e11d600, 0x0, 0x0)
        /usr/local/go/src/net/fd_unix.go:238 +0x42
net.(*TCPListener).accept(0xc00000f060, 0xc0004cede0, 0xc0004cede8, 0x18)
        /usr/local/go/src/net/tcpsock_posix.go:139 +0x32
net.(*TCPListener).Accept(0xc00000f060, 0x104e420, 0xc00008f800, 0x1174740, 0xc0000c2778)
        /usr/local/go/src/net/tcpsock.go:261 +0x47
google.golang.org/grpc.(*Server).Serve(0xc00008f800, 0x1167cc0, 0xc00000f060, 0x0, 0x0)
        /root/go/pkg/mod/google.golang.org/grpc@v1.25.1/server.go:597 +0x22e
github.com/lightninglabs/faraday/frdrpc.(*RPCServer).Start.func2(0xc0002f84b0)
        /root/go/src/github.com/lightninglabs/faraday/frdrpc/rpcserver.go:200 +0x85
created by github.com/lightninglabs/faraday/frdrpc.(*RPCServer).Start
        /root/go/src/github.com/lightninglabs/faraday/frdrpc/rpcserver.go:198 +0x626

goroutine 28 [select, 1 minutes]:
google.golang.org/grpc/internal/transport.(*controlBuffer).get(0xc0002f85f0, 0x1, 0x0, 0x0, 0x0, 0x0)
        /root/go/pkg/mod/google.golang.org/grpc@v1.25.1/internal/transport/controlbuf.go:395 +0x122
google.golang.org/grpc/internal/transport.(*loopyWriter).run(0xc0002a2540, 0x0, 0x0)
        /root/go/pkg/mod/google.golang.org/grpc@v1.25.1/internal/transport/controlbuf.go:513 +0x1e3
google.golang.org/grpc/internal/transport.newHTTP2Server.func2(0xc000344000)
        /root/go/pkg/mod/google.golang.org/grpc@v1.25.1/internal/transport/http2_server.go:290 +0xcb
created by google.golang.org/grpc/internal/transport.newHTTP2Server
        /root/go/pkg/mod/google.golang.org/grpc@v1.25.1/internal/transport/http2_server.go:287 +0xfe4

goroutine 29 [select, 1 minutes]:
google.golang.org/grpc/internal/transport.(*http2Server).keepalive(0xc000344000)
        /root/go/pkg/mod/google.golang.org/grpc@v1.25.1/internal/transport/http2_server.go:954 +0x1d6
created by google.golang.org/grpc/internal/transport.newHTTP2Server
        /root/go/pkg/mod/google.golang.org/grpc@v1.25.1/internal/transport/http2_server.go:296 +0x1009

goroutine 30 [IO wait, 1 minutes]:
internal/poll.runtime_pollWait(0x7f8bf24f3de8, 0x72, 0xffffffffffffffff)
        /usr/local/go/src/runtime/netpoll.go:184 +0x55
internal/poll.(*pollDesc).wait(0xc0004ac518, 0x72, 0x8000, 0x8000, 0xffffffffffffffff)
        /usr/local/go/src/internal/poll/fd_poll_runtime.go:87 +0x45
internal/poll.(*pollDesc).waitRead(...)
        /usr/local/go/src/internal/poll/fd_poll_runtime.go:92
internal/poll.(*FD).Read(0xc0004ac500, 0xc00032c000, 0x8000, 0x8000, 0x0, 0x0, 0x0)
        /usr/local/go/src/internal/poll/fd_unix.go:169 +0x1cf
net.(*netFD).Read(0xc0004ac500, 0xc00032c000, 0x8000, 0x8000, 0x0, 0x800010601, 0x0)
        /usr/local/go/src/net/fd_unix.go:202 +0x4f
net.(*conn).Read(0xc0000c2778, 0xc00032c000, 0x8000, 0x8000, 0x0, 0x0, 0x0)
        /usr/local/go/src/net/net.go:184 +0x68
bufio.(*Reader).Read(0xc000310120, 0xc00007e2d8, 0x9, 0x9, 0x4bde8a, 0x8000000000000000, 0x892f123d)
        /usr/local/go/src/bufio/bufio.go:226 +0x26a
io.ReadAtLeast(0x11519e0, 0xc000310120, 0xc00007e2d8, 0x9, 0x9, 0x9, 0xa1f375, 0xc0002f8658, 0xc0004d0e38)
        /usr/local/go/src/io/io.go:310 +0x87
io.ReadFull(...)
        /usr/local/go/src/io/io.go:329
golang.org/x/net/http2.readFrameHeader(0xc00007e2d8, 0x9, 0x9, 0x11519e0, 0xc000310120, 0x0, 0x0, 0x7070e0910100402, 0x0)
        /root/go/pkg/mod/golang.org/x/net@v0.0.0-20191002035440-2ec189313ef0/http2/frame.go:237 +0x87
golang.org/x/net/http2.(*Framer).ReadFrame(0xc00007e2a0, 0xc00024eb20, 0xc00024eb20, 0x0, 0x0)
        /root/go/pkg/mod/golang.org/x/net@v0.0.0-20191002035440-2ec189313ef0/http2/frame.go:492 +0xa1
google.golang.org/grpc/internal/transport.(*http2Server).HandleStreams(0xc000344000, 0xc000240c90, 0x104e478)
        /root/go/pkg/mod/google.golang.org/grpc@v1.25.1/internal/transport/http2_server.go:451 +0x9e
google.golang.org/grpc.(*Server).serveStreams(0xc00008f800, 0x1175940, 0xc000344000)
        /root/go/pkg/mod/google.golang.org/grpc@v1.25.1/server.go:718 +0xf3
google.golang.org/grpc.(*Server).handleRawConn.func1(0xc00008f800, 0x1175940, 0xc000344000)
        /root/go/pkg/mod/google.golang.org/grpc@v1.25.1/server.go:679 +0x3f
created by google.golang.org/grpc.(*Server).handleRawConn
        /root/go/pkg/mod/google.golang.org/grpc@v1.25.1/server.go:678 +0x562
```

**Comment by AbelLykens** [comment]
Increasing mem to 4096MB did not solve it.

**Comment by carlaKC** [comment]
For insights, we get a revenue report for each channel that gets all time forwarding history for your node to produce information about incoming/outgoing traffic and revenue. Does your node route heavily?  

I think there are a few things we can do here to address this:
1. Add start/end time to the `insights` endpoint
2. Limit insights to a single channel
3. Process forwarding events in memory more efficiently 

All of the above seem useful, so I will get going on some patches for you.

**Comment by AbelLykens** [comment]
Not sure about "heavily". 8k transactions this month, is that a lot?

**Comment by carlaKC** [comment]
> Not sure about "heavily". 8k transactions this month, is that a lot?

40 bytes per forward * 8k shouldn't be enough to give you problems.

**Comment by carlaKC** [comment]
@AbelLykens we had a bug in our pagination logic, which is why your node's 8k+ transactions hit it. Should be addressed if you run master, feel free to reopen if the issue is not addresses!

**Comment by AbelLykens** [comment]
You fixed it! Great thanks! Getting a reply within 1 second now!
